apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-install-pipeline
spec:
  params:
    - name: AdminEmailAddress
    - name: ReleaseName
    - name: Namespace
    - name: IngressSubDomain
    - name: IBM-Entitlement-Key-File
    - name: CD-Helm-Chart-Version
  workspaces:
    - name: entitlement-key
      description: Workspace for the IBM entitlement key file
  tasks:
    - name: ask-storageclass
      taskRef:
        name: openshift-cli
      params:
        - name: ARGS
          value:
            - "run"
            - "-i"
            - "--tty"
            - "--attach"
            - "pipeline"
            - "-n"
            - "$(params.Namespace)"
            - "-p"
            - "$(context.pipelineRun.name)"
            - "sh"
            - "-c"
            - "echo 'Enter the desired storage class type (e.g., gp2, io1):'; read storageClass; echo 'storageClass=$storageClass' > /workspace/storageclass"
      workspaces:
        - name: shared-data
          workspace: entitlement-key

    - name: install-cd
      taskRef:
        name: helm-install
      runAfter: ["ask-storageclass"]
      params:
        - name: CHART_REF
          value: "$(params.CD-Helm-Chart-Version)"
        - name: RELEASE_NAME
          value: "$(params.ReleaseName)"
        - name: NAMESPACE
          value: "$(params.Namespace)"
        - name: VALUES_FILE
          value: /workspace/cd-helm-values.yaml
      env:
        - name: HELM_EXPERIMENTAL_OCI
          value: "1"
      workspaces:
        - name: entitlement-key
          workspace: entitlement-key
        - name: shared-data
          workspace: shared-data

  finally:
    - name: notify-admin
      taskRef:
        name: openshift-client
      params:
        - name: ARGS
          value:
            - "run"
            - "-i"
            - "--tty"
            - "--attach"
            - "pipeline"
            - "-n"
            - "$(params.Namespace)"
            - "-p"
            - "$(context.pipelineRun.name)"
            - "sh"
            - "-c"
            - "echo 'Deployment complete!' | mail -s 'CD Deployment Status' $(params.AdminEmailAddress)"