apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-datapower-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-datapower-operator-1.9.0-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/datapower-operator-catalog@sha256:709199367366fe22ffd9791a975e268f736903b55605eff99f031982bf9b4c68
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
