apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-integration-operatorgroup
  labels:
    backup.integration.ibm.com/component: operatorgroup     
  namespace: integration           
spec:
  targetNamespaces:
  - integration